src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $DateDebut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $DateFin = null;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: Categorie::class)]
    private Collection $categories;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    /**
     * @return Collection<int, Categorie>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categorie $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->setEvent($this);
        }

        return $this;
    }

    public function removeCategory(Categorie $category): self
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getEvent() === $this) {
                $category->setEvent(null);
            }
        }

        return $this;
    }







}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\Event;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('DateDebut')
            ->add('DateFin')

            ->add('submit',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EventController extends AbstractController
{
    #[Route('/event', name: 'app_event')]
    public function index(): Response
    {
        return $this->render('event/index.html.twig', [
            'controller_name' => 'EventController',
        ]);
    }
    #[Route('/events', name: 'app_events')]
    public function listevent(EventRepository $repository){

        $event=$repository->findAll();
        return $this->render("event/listevent.html.twig",array("tabevents"=>$event));

    }
    #[Route('/addevent', name: 'app_addevent')]
    public function addClub(ManagerRegistry $doctrine,Request $request)
    {
        $event= new Event();
        $form=$this->createForm(EventType::class,$event);
        $form->handleRequest($request);
        if($form->isSubmitted()){
            $em =$doctrine->getManager();
            $em->persist($event);
            $em->flush();
            return $this->redirectToRoute("app_events");
        }
        return $this->renderForm("event/addevent.html.twig",array("formEvent"=>$form));
    }
    #[Route('/update/{id}', name: 'app_updatevent')]
    public function update(EventRepository $repository,$id,ManagerRegistry $doctrine,Request $request){

        $event=$repository->find($id);
        $form=$this->createForm(EventType::class,$event);
        $form->handleRequest($request);
        if($form->isSubmitted()){
            $em =$doctrine->getManager();
            $em->flush();
            return $this->redirectToRoute("app_events");
        }
        return $this->renderForm("club/addevent.html.twig",
            array("formEvent"=>$form));

    }
}

templates/event/addevent.html.twig
<h4>Add event</h4>
{{form(formEvent)}}

templates/event/deletevent.html.twig
<h4>delete event</h4>
{{ form(formEvent) }}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EventController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/workshopsymfony-amirakhalfy/src/Controller/EventController.php'|file_link(0) }}">src/Controller/EventController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/workshopsymfony-amirakhalfy/templates/event/index.html.twig'|file_link(0) }}">templates/event/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/event/listevent.html.twig
<h1>liste des classroom</h1>
<td><a href="{{ path('app_addevent') }}" >ajouter classroom</a></td>
<table border="1">
    <tr>
        <th>id</th>
        <th>name</th>
    </tr>
    <tr>
        {% for i in tabevents %}
        <td>{{ i.id }}</td>
        <td>{{ i.title|upper}}</td>
        <td>{{ i.dateDebut}}</td>
        <td>{{ i.dateFin}}</td>
        <td>{{ i.categorie.id}}</td>
        <td><a href="{{ path('app_updatevent',{'id':i.id})}}" >modifier</a></td>


    </tr>
    {% endfor %}

</table>